export default {
  "clean-code": {
    titulo: "Código Limpo",
    autor: "Robert C. Martin",
    ano: 2008,
    genero: ["Tecnologia", "Programação", "Desenvolvimento de Software"],
    paginas: 425,
    capa: "https://i.ibb.co/Xxvc7hs/9bf9.jpg",
    descricao: "Mesmo um código ruim pod...",
    avaliacao: 4.8,
    capaDura: true,
  },
  sapiens: {
    titulo: "Sapiens: Uma Breve História da Humanidade",
    autor: "Yuval Noah Harari",
    ano: 2011,
    genero: ["História", "Ciência"],
    paginas: 464,
    capa: "https://i.ibb.co/KcW2Rg9Y/sapiens.jpg",
    descricao: "Uma breve história da humanidade",
    avaliacao: 4.6,
    capaDura: true,
  },
  "o-poder-do-habito": {
    titulo: "O Poder do Hábito",
    autor: "Charles Duhigg",
    ano: 2012,
    genero: ["Autoajuda", "Desenvolvimento Pessoal"],
    paginas: 322,
    capa: "https://m.magazineluiza.com.br/a-static/420x420/livro-o-poder-do-habito-objetiva/leituraterraco/9788539004119/3d4b884b3705ea387d1dd7bb41bd4627.jpeg",
    descricao:
      "Um guia prático sobre como formar bons hábitos e quebrar os ruins",
    avaliacao: 4.5,
    capaDura: true,
  },

  "dom-casmurro": {
    titulo: "Dom Casmurro",
    autor: "Machado de Assis",
    ano: 1899,
    genero: ["Romance", "Literatura Brasileira"],
    paginas: 256,
    capa: "https://i.ibb.co/VWBYsWgr/casmurro.jpg",
    descricao: "A história de Bentinho e sua obsessão por Capitu.",
    avaliacao: 4.4,
    capaDura: false,
  },

  1984: {
    titulo: "1984",
    autor: "George Orwell",
    ano: 1949,
    genero: ["Distopia", "Ficção Científica"],
    paginas: 328,
    capa: "https://i.ibb.co/zV8pCBm/1984.jpg",
    descricao: "Um futuro distópico sob vigilância constante.",
    avaliacao: 4.7,
    capaDura: false,
  },

  "pai-rico-pai-pobre": {
    titulo: "Pai Rico, Pai Pobre",
    autor: "Robert T. Kiyosaki",
    ano: 1997,
    genero: ["Finanças", "Educação Financeira"],
    paginas: 336,
    capa: "https://i.ibb.co/Dgt67TdG/pai-rico.jpg",
    descricao: "Lições sobre dinheiro que não são ensinadas na escola.",
    avaliacao: 4.3,
    capaDura: true,
  },

  "o-senhor-dos-aneis": {
    titulo: "O Senhor dos Anéis: A Sociedade do Anel",
    autor: "J.R.R. Tolkien",
    ano: 1954,
    genero: ["Fantasia", "Aventura"],
    paginas: 576,
    capa: "https://i.ibb.co/4fRjMch/senhor-dos-aneis.jpg",
    descricao: "Uma jornada épica para destruir o Um Anel.",
    avaliacao: 4.9,
    capaDura: true,
  },

  "codigo-da-vinci": {
    titulo: "O Código Da Vinci",
    autor: "Dan Brown",
    ano: 2003,
    genero: ["Suspense", "Mistério"],
    paginas: 480,
    capa: "https://i.ibb.co/KyQN5zN/codigo-da-vinci.jpg",
    descricao: "Um suspense envolvendo arte, religiões e segredos antigos.",
    avaliacao: 4.2,
    capaDura: false,
  },
};
